name: Clone Upstream and Run Local Script

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

jobs:
    clone-and-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout current repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Clone upstream repository
              run: |
                  set -euo pipefail
                  git clone https://github.com/Anduin2017/HowToCook.git upstream

            - name: Setup Python, install deps, copy script and run
              run: |
                  python -m pip install --upgrade pip
                  pip install markdown beautifulsoup4

                  cp main.py upstream/
                  cd upstream

                  python main.py

                  cd ..

                  mv upstream/recipes.json recipes.json
                  mv upstream/filtered_recipes.json filtered_recipes.json

                  rm -rf upstream

            - name: Commit and push changes
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

                  git add recipes.json

                  if git diff --cached --quiet; then
                  echo "No changes to commit"
                  else
                  git commit -m "Update recipes.json from upstream"
                  git push origin HEAD:main
                  fi
