name: Clone Upstream and Create PR with Generated Files

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # 每天 0 点运行

# 允许该 workflow 创建 PR 和推送分支
permissions:
  contents: write
  pull-requests: write

jobs:
  clone-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Clone upstream repository
        run: |
          git clone https://github.com/Anduin2017/HowToCook.git upstream

      - name: Setup Python, install deps, copy script and run
        run: |
          python -m pip install --upgrade pip
          pip install markdown beautifulsoup4
          cp main.py upstream/
          cp ignore.json upstream/
          cd upstream
          python main.py
          cd ..
          mv upstream/recipes.json recipes.json
          mv upstream/filtered_recipes.json filtered_recipes.json
          rm -rf upstream

      - name: Prepare commit for generated recipe files
        id: prepare
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add recipes.json filtered_recipes.json || true
          if git diff --cached --quiet; then
            echo "no-changes=true" >> $GITHUB_OUTPUT
          else
            git commit -m "CI: update generated recipes files from upstream"
            echo "no-changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request with updated files
        if: steps.prepare.outputs.no-changes == 'false'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "CI: update generated recipes files from upstream"
          branch: "update/recipes-from-upstream-${{ github.run_id }}"
          title: "Update generated recipes files from upstream"
          body: |
            This PR updates the generated recipe files (`recipes.json` and `filtered_recipes.json`) produced by CI from upstream HowToCook.
          base: main
